-- techno-viking-light.lua — paper white + deep magenta colorscheme.
-- Light sibling of techno-viking (same local Omacase plugin). Bright accents are
-- deepened for contrast on light; the bright magenta is reserved for fills.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "techno-viking-light"
vim.o.background = "light"
vim.o.termguicolors = true

local c = {
  bg          = "#F5F2F4",
  bg_float    = "#ECE7EA",
  surface     = "#EAE3E8",
  surface2    = "#DFD6DD",
  border      = "#CDBFC8",
  border_soft = "#E0D8DD",
  text        = "#2A2230",
  muted       = "#6E6470",
  dim         = "#9B8F98",
  accent      = "#C21B86", -- deep magenta (functions, primary)
  accent_alt  = "#A8197A", -- keywords
  accent_dk   = "#8A1E6E", -- types
  accent_brt  = "#F12EAF", -- bright magenta — fills only
  green       = "#1F9D6A",
  yellow      = "#C8910A",
  red         = "#CC2F2C",
  blue        = "#3C6E82",
  cyan        = "#2D7E8C",
}

local hl = vim.api.nvim_set_hl
local function set(groups)
  for name, spec in pairs(groups) do
    hl(0, name, spec)
  end
end

set({
  -- ── Editor / UI ───────────────────────────────────────
  Normal       = { fg = c.text, bg = c.bg },
  NormalNC     = { fg = c.muted, bg = c.bg },
  NormalFloat  = { fg = c.text, bg = c.bg_float },
  FloatBorder  = { fg = c.border, bg = c.bg_float },
  FloatTitle   = { fg = c.accent, bg = c.bg_float, bold = true },
  Cursor       = { fg = c.bg, bg = c.accent },
  CursorLine   = { bg = c.surface },
  CursorColumn = { bg = c.surface },
  ColorColumn  = { bg = c.surface },
  LineNr       = { fg = c.dim },
  CursorLineNr = { fg = c.accent, bold = true },
  SignColumn   = { fg = c.dim, bg = c.bg },
  WinSeparator = { fg = c.border },
  VertSplit    = { fg = c.border },
  EndOfBuffer  = { fg = c.border_soft },
  Folded       = { fg = c.muted, bg = c.surface },
  FoldColumn   = { fg = c.dim, bg = c.bg },
  NonText      = { fg = c.border },
  SpecialKey   = { fg = c.border },
  Whitespace   = { fg = c.border },
  Visual       = { bg = c.surface2 },
  VisualNOS    = { bg = c.surface2 },
  Search       = { fg = c.bg, bg = c.yellow },
  IncSearch    = { fg = c.bg, bg = c.accent_brt },
  CurSearch    = { fg = c.bg, bg = c.accent_brt },
  MatchParen   = { fg = c.accent, bg = c.surface2, bold = true },
  WildMenu     = { fg = c.bg, bg = c.accent },
  Directory    = { fg = c.accent },
  Title        = { fg = c.accent, bold = true },
  ModeMsg      = { fg = c.text, bold = true },
  MoreMsg      = { fg = c.green },
  Question     = { fg = c.green },
  WarningMsg   = { fg = c.yellow },
  ErrorMsg     = { fg = c.red },
  Conceal      = { fg = c.dim },
  QuickFixLine = { bg = c.surface2 },
  Winbar       = { fg = c.muted, bg = c.bg },
  WinbarNC     = { fg = c.dim, bg = c.bg },

  -- ── Popup menu ────────────────────────────────────────
  Pmenu        = { fg = c.text, bg = c.bg_float },
  PmenuSel     = { fg = c.bg, bg = c.accent, bold = true },
  PmenuSbar    = { bg = c.surface2 },
  PmenuThumb   = { bg = c.border },

  -- ── Status / tab line ─────────────────────────────────
  StatusLine   = { fg = c.text, bg = c.surface, bold = true },
  StatusLineNC = { fg = c.dim, bg = c.surface },
  TabLine      = { fg = c.muted, bg = c.surface },
  TabLineFill  = { bg = c.surface },
  TabLineSel   = { fg = c.accent, bg = c.bg, bold = true },

  -- ── Classic syntax ────────────────────────────────────
  Comment      = { fg = c.dim, italic = true },
  Constant     = { fg = c.yellow },
  String       = { fg = c.green },
  Character    = { fg = c.green },
  Number       = { fg = c.yellow },
  Boolean      = { fg = c.yellow },
  Float        = { fg = c.yellow },
  Identifier   = { fg = c.text },
  Function     = { fg = c.accent, bold = true },
  Statement    = { fg = c.accent_alt },
  Conditional  = { fg = c.accent_alt },
  Repeat       = { fg = c.accent_alt },
  Label        = { fg = c.accent_alt },
  Operator     = { fg = c.muted },
  Keyword      = { fg = c.accent_alt },
  Exception    = { fg = c.red },
  PreProc      = { fg = c.yellow },
  Include      = { fg = c.accent_alt },
  Define       = { fg = c.yellow },
  Macro        = { fg = c.yellow },
  PreCondit    = { fg = c.yellow },
  Type         = { fg = c.accent_dk },
  StorageClass = { fg = c.accent_dk },
  Structure    = { fg = c.accent_dk },
  Typedef      = { fg = c.accent_dk },
  Special      = { fg = c.yellow },
  SpecialChar  = { fg = c.yellow },
  Delimiter    = { fg = c.muted },
  Tag          = { fg = c.accent },
  Debug        = { fg = c.red },
  Underlined   = { fg = c.accent, underline = true },
  Error        = { fg = c.red, bg = "#F7E3E2", bold = true },
  Todo         = { fg = c.bg, bg = c.yellow, bold = true },

  -- ── Treesitter (@…) ───────────────────────────────────
  ["@comment"]              = { link = "Comment" },
  ["@comment.todo"]         = { fg = c.bg, bg = c.yellow, bold = true },
  ["@comment.note"]         = { fg = c.bg, bg = c.green, bold = true },
  ["@comment.warning"]      = { fg = c.bg, bg = c.yellow, bold = true },
  ["@comment.error"]        = { fg = c.bg, bg = c.red, bold = true },
  ["@variable"]             = { fg = c.text },
  ["@variable.builtin"]     = { fg = c.accent_alt, italic = true },
  ["@variable.parameter"]   = { fg = c.text },
  ["@variable.member"]      = { fg = c.cyan },
  ["@constant"]             = { fg = c.yellow },
  ["@constant.builtin"]     = { fg = c.yellow },
  ["@constant.macro"]       = { fg = c.yellow },
  ["@module"]               = { fg = c.accent_dk },
  ["@string"]               = { fg = c.green },
  ["@string.escape"]        = { fg = c.cyan },
  ["@string.special"]       = { fg = c.cyan },
  ["@character"]            = { fg = c.green },
  ["@number"]               = { fg = c.yellow },
  ["@boolean"]              = { fg = c.yellow },
  ["@float"]                = { fg = c.yellow },
  ["@function"]             = { fg = c.accent, bold = true },
  ["@function.builtin"]     = { fg = c.accent_alt },
  ["@function.call"]        = { fg = c.accent },
  ["@function.macro"]       = { fg = c.yellow },
  ["@constructor"]          = { fg = c.accent_dk },
  ["@method"]               = { fg = c.accent, bold = true },
  ["@method.call"]          = { fg = c.accent },
  ["@keyword"]              = { fg = c.accent_alt },
  ["@keyword.function"]     = { fg = c.accent_alt },
  ["@keyword.operator"]     = { fg = c.accent_alt },
  ["@keyword.return"]       = { fg = c.accent_alt },
  ["@keyword.import"]       = { fg = c.accent_alt },
  ["@keyword.conditional"]  = { fg = c.accent_alt },
  ["@keyword.repeat"]       = { fg = c.accent_alt },
  ["@keyword.exception"]    = { fg = c.red },
  ["@operator"]             = { fg = c.muted },
  ["@type"]                 = { fg = c.accent_dk },
  ["@type.builtin"]         = { fg = c.accent_dk, italic = true },
  ["@type.definition"]      = { fg = c.accent_dk },
  ["@property"]             = { fg = c.cyan },
  ["@field"]                = { fg = c.cyan },
  ["@parameter"]            = { fg = c.text },
  ["@punctuation.delimiter"]= { fg = c.muted },
  ["@punctuation.bracket"]  = { fg = c.muted },
  ["@punctuation.special"]  = { fg = c.accent_alt },
  ["@tag"]                  = { fg = c.accent },
  ["@tag.attribute"]        = { fg = c.yellow },
  ["@tag.delimiter"]        = { fg = c.muted },
  ["@markup.heading"]       = { fg = c.accent, bold = true },
  ["@markup.strong"]        = { fg = c.text, bold = true },
  ["@markup.italic"]        = { fg = c.text, italic = true },
  ["@markup.link"]          = { fg = c.accent_alt, underline = true },
  ["@markup.raw"]           = { fg = c.green },
  ["@markup.list"]          = { fg = c.accent_alt },
  ["@diff.plus"]            = { fg = c.green },
  ["@diff.minus"]           = { fg = c.red },
  ["@diff.delta"]           = { fg = c.yellow },

  -- ── LSP semantic tokens ───────────────────────────────
  ["@lsp.type.function"]      = { link = "@function" },
  ["@lsp.type.method"]        = { link = "@method" },
  ["@lsp.type.variable"]      = { link = "@variable" },
  ["@lsp.type.parameter"]     = { link = "@parameter" },
  ["@lsp.type.property"]      = { link = "@property" },
  ["@lsp.type.class"]         = { link = "@type" },
  ["@lsp.type.type"]          = { link = "@type" },
  ["@lsp.type.enum"]          = { link = "@type" },
  ["@lsp.type.interface"]     = { link = "@type" },
  ["@lsp.type.namespace"]     = { link = "@module" },
  ["@lsp.type.keyword"]       = { link = "@keyword" },
  ["@lsp.type.string"]        = { link = "@string" },
  ["@lsp.type.number"]        = { link = "@number" },
  ["@lsp.type.comment"]       = { link = "@comment" },
  ["@lsp.type.decorator"]     = { fg = c.accent_alt },
  ["@lsp.mod.readonly"]       = { fg = c.yellow },

  -- ── Diagnostics ───────────────────────────────────────
  DiagnosticError = { fg = c.red },
  DiagnosticWarn  = { fg = c.yellow },
  DiagnosticInfo  = { fg = c.cyan },
  DiagnosticHint  = { fg = c.muted },
  DiagnosticOk    = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn  = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo  = { sp = c.cyan, undercurl = true },
  DiagnosticUnderlineHint  = { sp = c.muted, undercurl = true },
  DiagnosticVirtualTextError = { fg = c.red, bg = "#F7E3E2" },
  DiagnosticVirtualTextWarn  = { fg = c.yellow, bg = "#F3EEDD" },
  DiagnosticVirtualTextInfo  = { fg = c.cyan, bg = c.surface },
  DiagnosticVirtualTextHint  = { fg = c.muted, bg = c.surface },

  -- ── Diff / git ────────────────────────────────────────
  DiffAdd       = { fg = c.green, bg = "#E2F3EA" },
  DiffChange    = { fg = c.yellow, bg = "#F3EEDD" },
  DiffDelete    = { fg = c.red, bg = "#F7E3E2" },
  DiffText      = { fg = c.accent, bg = "#F3DEEC", bold = true },
  Added         = { fg = c.green },
  Changed       = { fg = c.yellow },
  Removed       = { fg = c.red },
  GitSignsAdd       = { fg = c.green, bg = c.bg },
  GitSignsChange    = { fg = c.yellow, bg = c.bg },
  GitSignsDelete    = { fg = c.red, bg = c.bg },

  -- ── Spell ─────────────────────────────────────────────
  SpellBad   = { sp = c.red, undercurl = true },
  SpellCap   = { sp = c.yellow, undercurl = true },
  SpellRare  = { sp = c.accent_alt, undercurl = true },
  SpellLocal = { sp = c.green, undercurl = true },

  -- ── Common plugins (Telescope / WhichKey / trees) ─────
  TelescopeNormal       = { fg = c.text, bg = c.bg_float },
  TelescopeBorder       = { fg = c.border, bg = c.bg_float },
  TelescopeTitle        = { fg = c.accent, bold = true },
  TelescopePromptNormal = { fg = c.text, bg = c.surface },
  TelescopePromptBorder = { fg = c.surface, bg = c.surface },
  TelescopePromptPrefix = { fg = c.accent },
  TelescopeSelection    = { fg = c.text, bg = c.surface2 },
  TelescopeMatching     = { fg = c.accent, bold = true },
  WhichKey            = { fg = c.accent },
  WhichKeyGroup       = { fg = c.accent_alt },
  WhichKeyDesc        = { fg = c.text },
  WhichKeySeparator   = { fg = c.dim },
  WhichKeyFloat       = { bg = c.bg_float },
  NeoTreeNormal       = { fg = c.text, bg = c.bg_float },
  NeoTreeNormalNC     = { fg = c.muted, bg = c.bg_float },
  NeoTreeDirectoryIcon= { fg = c.accent },
  NeoTreeGitModified  = { fg = c.yellow },
  NeoTreeGitAdded     = { fg = c.green },
  NeoTreeGitDeleted   = { fg = c.red },
  IblIndent           = { fg = c.border_soft },
  IblScope            = { fg = c.border },
  LspInlayHint        = { fg = c.dim, bg = c.surface },
  LspReferenceText    = { bg = c.surface2 },
  LspReferenceRead    = { bg = c.surface2 },
  LspReferenceWrite   = { bg = c.surface2 },
})
