-- techno-viking.lua — dark slate + electric magenta colorscheme.
-- Local Omacase nvim plugin (loaded via the `dir` spec in lua/plugins/colorscheme.lua).
-- Source palette: techno-viking-ui/theme.css.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "techno-viking"
vim.o.background = "dark"
vim.o.termguicolors = true

local c = {
  bg          = "#0B1012",
  bg_deep     = "#07090A",
  surface     = "#141A1D",
  surface2    = "#1C2326",
  border      = "#2A3438",
  border_soft = "#1F272A",
  text        = "#E8E7E5",
  muted       = "#8B9499",
  dim         = "#5A6469",
  accent      = "#F12EAF", -- electric magenta
  accent_hi   = "#FF5BC5",
  accent_lo   = "#B81E84",
  green       = "#5CE0A8",
  yellow      = "#F2C94C",
  red         = "#FF5C5C",
  blue        = "#6B8FA0",
  cyan        = "#7DB5C0",
}

local hl = vim.api.nvim_set_hl
local function set(groups)
  for name, spec in pairs(groups) do
    hl(0, name, spec)
  end
end

set({
  -- ── Editor / UI ───────────────────────────────────────
  Normal       = { fg = c.text, bg = c.bg },
  NormalNC     = { fg = c.muted, bg = c.bg },
  NormalFloat  = { fg = c.text, bg = c.bg_deep },
  FloatBorder  = { fg = c.border, bg = c.bg_deep },
  FloatTitle   = { fg = c.accent, bg = c.bg_deep, bold = true },
  Cursor       = { fg = c.bg, bg = c.accent },
  CursorLine   = { bg = c.surface },
  CursorColumn = { bg = c.surface },
  ColorColumn  = { bg = c.surface },
  LineNr       = { fg = c.border },
  CursorLineNr = { fg = c.accent, bold = true },
  SignColumn   = { fg = c.border, bg = c.bg },
  WinSeparator = { fg = c.border_soft },
  VertSplit    = { fg = c.border_soft },
  EndOfBuffer  = { fg = c.surface },
  Folded       = { fg = c.dim, bg = c.surface },
  FoldColumn   = { fg = c.border, bg = c.bg },
  NonText      = { fg = c.border_soft },
  SpecialKey   = { fg = c.border_soft },
  Whitespace   = { fg = c.border_soft },
  Visual       = { bg = c.surface2 },
  VisualNOS    = { bg = c.surface2 },
  Search       = { fg = c.bg, bg = c.yellow },
  IncSearch    = { fg = c.bg, bg = c.accent },
  CurSearch    = { fg = c.bg, bg = c.accent },
  MatchParen   = { fg = c.accent, bg = c.border, bold = true },
  WildMenu     = { fg = c.bg, bg = c.accent },
  Directory    = { fg = c.accent },
  Title        = { fg = c.accent, bold = true },
  ModeMsg      = { fg = c.text, bold = true },
  MoreMsg      = { fg = c.green },
  Question     = { fg = c.green },
  WarningMsg   = { fg = c.yellow },
  ErrorMsg     = { fg = c.red },
  Conceal      = { fg = c.dim },
  QuickFixLine = { bg = c.surface2 },
  Winbar       = { fg = c.muted, bg = c.bg },
  WinbarNC     = { fg = c.dim, bg = c.bg },

  -- ── Popup menu ────────────────────────────────────────
  Pmenu        = { fg = c.text, bg = c.surface },
  PmenuSel     = { fg = c.bg, bg = c.accent, bold = true },
  PmenuSbar    = { bg = c.surface2 },
  PmenuThumb   = { bg = c.border },

  -- ── Status / tab line ─────────────────────────────────
  StatusLine   = { fg = c.text, bg = c.surface, bold = true },
  StatusLineNC = { fg = c.dim, bg = c.surface },
  TabLine      = { fg = c.dim, bg = c.surface },
  TabLineFill  = { bg = c.surface },
  TabLineSel   = { fg = c.accent, bg = c.bg, bold = true },

  -- ── Classic syntax ────────────────────────────────────
  Comment      = { fg = c.dim, italic = true },
  Constant     = { fg = c.yellow },
  String       = { fg = c.green },
  Character    = { fg = c.green },
  Number       = { fg = c.yellow },
  Boolean      = { fg = c.yellow },
  Float        = { fg = c.yellow },
  Identifier   = { fg = c.text },
  Function     = { fg = c.accent, bold = true },
  Statement    = { fg = c.accent_hi },
  Conditional  = { fg = c.accent_hi },
  Repeat       = { fg = c.accent_hi },
  Label        = { fg = c.accent_hi },
  Operator     = { fg = c.muted },
  Keyword      = { fg = c.accent_hi },
  Exception    = { fg = c.red },
  PreProc      = { fg = c.yellow },
  Include      = { fg = c.accent_hi },
  Define       = { fg = c.yellow },
  Macro        = { fg = c.yellow },
  PreCondit    = { fg = c.yellow },
  Type         = { fg = c.accent_lo },
  StorageClass = { fg = c.accent_lo },
  Structure    = { fg = c.accent_lo },
  Typedef      = { fg = c.accent_lo },
  Special      = { fg = c.yellow },
  SpecialChar  = { fg = c.yellow },
  Delimiter    = { fg = c.muted },
  Tag          = { fg = c.accent },
  Debug        = { fg = c.red },
  Underlined   = { fg = c.accent, underline = true },
  Error        = { fg = c.red, bg = "#1C1010", bold = true },
  Todo         = { fg = c.yellow, bold = true },

  -- ── Treesitter (@…) ───────────────────────────────────
  ["@comment"]              = { link = "Comment" },
  ["@comment.todo"]         = { fg = c.bg, bg = c.yellow, bold = true },
  ["@comment.note"]         = { fg = c.bg, bg = c.green, bold = true },
  ["@comment.warning"]      = { fg = c.bg, bg = c.yellow, bold = true },
  ["@comment.error"]        = { fg = c.bg, bg = c.red, bold = true },
  ["@variable"]             = { fg = c.text },
  ["@variable.builtin"]     = { fg = c.accent_hi, italic = true },
  ["@variable.parameter"]   = { fg = c.text },
  ["@variable.member"]      = { fg = c.cyan },
  ["@constant"]             = { fg = c.yellow },
  ["@constant.builtin"]     = { fg = c.yellow },
  ["@constant.macro"]       = { fg = c.yellow },
  ["@module"]               = { fg = c.accent_lo },
  ["@string"]               = { fg = c.green },
  ["@string.escape"]        = { fg = c.cyan },
  ["@string.special"]       = { fg = c.cyan },
  ["@character"]            = { fg = c.green },
  ["@number"]               = { fg = c.yellow },
  ["@boolean"]              = { fg = c.yellow },
  ["@float"]                = { fg = c.yellow },
  ["@function"]             = { fg = c.accent, bold = true },
  ["@function.builtin"]     = { fg = c.accent_hi },
  ["@function.call"]        = { fg = c.accent },
  ["@function.macro"]       = { fg = c.yellow },
  ["@constructor"]          = { fg = c.accent_lo },
  ["@method"]               = { fg = c.accent, bold = true },
  ["@method.call"]          = { fg = c.accent },
  ["@keyword"]              = { fg = c.accent_hi },
  ["@keyword.function"]     = { fg = c.accent_hi },
  ["@keyword.operator"]     = { fg = c.accent_hi },
  ["@keyword.return"]       = { fg = c.accent_hi },
  ["@keyword.import"]       = { fg = c.accent_hi },
  ["@keyword.conditional"]  = { fg = c.accent_hi },
  ["@keyword.repeat"]       = { fg = c.accent_hi },
  ["@keyword.exception"]    = { fg = c.red },
  ["@operator"]             = { fg = c.muted },
  ["@type"]                 = { fg = c.accent_lo },
  ["@type.builtin"]         = { fg = c.accent_lo, italic = true },
  ["@type.definition"]      = { fg = c.accent_lo },
  ["@property"]             = { fg = c.cyan },
  ["@field"]                = { fg = c.cyan },
  ["@parameter"]            = { fg = c.text },
  ["@punctuation.delimiter"]= { fg = c.muted },
  ["@punctuation.bracket"]  = { fg = c.muted },
  ["@punctuation.special"]  = { fg = c.accent_hi },
  ["@tag"]                  = { fg = c.accent },
  ["@tag.attribute"]        = { fg = c.yellow },
  ["@tag.delimiter"]        = { fg = c.muted },
  ["@markup.heading"]       = { fg = c.accent, bold = true },
  ["@markup.strong"]        = { fg = c.text, bold = true },
  ["@markup.italic"]        = { fg = c.text, italic = true },
  ["@markup.link"]          = { fg = c.accent_hi, underline = true },
  ["@markup.raw"]           = { fg = c.green },
  ["@markup.list"]          = { fg = c.accent_hi },
  ["@diff.plus"]            = { fg = c.green },
  ["@diff.minus"]           = { fg = c.red },
  ["@diff.delta"]           = { fg = c.yellow },

  -- ── LSP semantic tokens ───────────────────────────────
  ["@lsp.type.function"]      = { link = "@function" },
  ["@lsp.type.method"]        = { link = "@method" },
  ["@lsp.type.variable"]      = { link = "@variable" },
  ["@lsp.type.parameter"]     = { link = "@parameter" },
  ["@lsp.type.property"]      = { link = "@property" },
  ["@lsp.type.class"]         = { link = "@type" },
  ["@lsp.type.type"]          = { link = "@type" },
  ["@lsp.type.enum"]          = { link = "@type" },
  ["@lsp.type.interface"]     = { link = "@type" },
  ["@lsp.type.namespace"]     = { link = "@module" },
  ["@lsp.type.keyword"]       = { link = "@keyword" },
  ["@lsp.type.string"]        = { link = "@string" },
  ["@lsp.type.number"]        = { link = "@number" },
  ["@lsp.type.comment"]       = { link = "@comment" },
  ["@lsp.type.decorator"]     = { fg = c.accent_hi },
  ["@lsp.mod.readonly"]       = { fg = c.yellow },

  -- ── Diagnostics ───────────────────────────────────────
  DiagnosticError = { fg = c.red },
  DiagnosticWarn  = { fg = c.yellow },
  DiagnosticInfo  = { fg = c.cyan },
  DiagnosticHint  = { fg = c.dim },
  DiagnosticOk    = { fg = c.green },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn  = { sp = c.yellow, undercurl = true },
  DiagnosticUnderlineInfo  = { sp = c.cyan, undercurl = true },
  DiagnosticUnderlineHint  = { sp = c.dim, undercurl = true },
  DiagnosticVirtualTextError = { fg = c.red, bg = "#241010" },
  DiagnosticVirtualTextWarn  = { fg = c.yellow, bg = "#241F0F" },
  DiagnosticVirtualTextInfo  = { fg = c.cyan, bg = c.surface },
  DiagnosticVirtualTextHint  = { fg = c.dim, bg = c.surface },

  -- ── Diff / git ────────────────────────────────────────
  DiffAdd       = { fg = c.green, bg = "#0F2418" },
  DiffChange    = { fg = c.yellow, bg = "#241F0F" },
  DiffDelete    = { fg = c.red, bg = "#241010" },
  DiffText      = { fg = c.accent, bg = "#2A1422", bold = true },
  Added         = { fg = c.green },
  Changed       = { fg = c.yellow },
  Removed       = { fg = c.red },
  GitSignsAdd       = { fg = c.green, bg = c.bg },
  GitSignsChange    = { fg = c.yellow, bg = c.bg },
  GitSignsDelete    = { fg = c.red, bg = c.bg },

  -- ── Spell ─────────────────────────────────────────────
  SpellBad   = { sp = c.red, undercurl = true },
  SpellCap   = { sp = c.yellow, undercurl = true },
  SpellRare  = { sp = c.accent_hi, undercurl = true },
  SpellLocal = { sp = c.green, undercurl = true },

  -- ── Common plugins (Telescope / WhichKey / trees) ─────
  TelescopeNormal       = { fg = c.text, bg = c.bg_deep },
  TelescopeBorder       = { fg = c.border, bg = c.bg_deep },
  TelescopeTitle        = { fg = c.accent, bold = true },
  TelescopePromptNormal = { fg = c.text, bg = c.surface },
  TelescopePromptBorder = { fg = c.surface, bg = c.surface },
  TelescopePromptPrefix = { fg = c.accent },
  TelescopeSelection    = { fg = c.text, bg = c.surface2 },
  TelescopeMatching     = { fg = c.accent, bold = true },
  WhichKey            = { fg = c.accent },
  WhichKeyGroup       = { fg = c.accent_hi },
  WhichKeyDesc        = { fg = c.text },
  WhichKeySeparator   = { fg = c.dim },
  WhichKeyFloat       = { bg = c.bg_deep },
  NeoTreeNormal       = { fg = c.text, bg = c.bg_deep },
  NeoTreeNormalNC     = { fg = c.muted, bg = c.bg_deep },
  NeoTreeDirectoryIcon= { fg = c.accent },
  NeoTreeGitModified  = { fg = c.yellow },
  NeoTreeGitAdded     = { fg = c.green },
  NeoTreeGitDeleted   = { fg = c.red },
  IblIndent           = { fg = c.border_soft },
  IblScope            = { fg = c.border },
  LspInlayHint        = { fg = c.dim, bg = c.surface },
  LspReferenceText    = { bg = c.surface2 },
  LspReferenceRead    = { bg = c.surface2 },
  LspReferenceWrite   = { bg = c.surface2 },
})
